version: '3'
services:
  client:
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      app_network:
        ipv4_address: 172.20.0.2

  server:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      app_network:
        ipv4_address: 172.20.0.3

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16